#!/bin/bash
#seq=TEST1
#seq=TEST2
#seq=TEST3
#seq=TEST4         
#seq=TEST5
#seq=TEST6         
#seq=TEST7
#seq=TEST8
seq=TEST9
#seq=TEST10
#seq=TEST11
#seq=TEST12

rm -rf work; 
vlib work;
UVM_FLAGS = +incdir+${UVM_HOME}/src ${UVM_HOME}/src/uvm_pkg.
if [ "$seq" == "TEST10" ]; 
then
    vlog -timescale=1ns/1ns -sv +acc ${UVM_FLAGS} -incr -f filelist_tb.f -assertdebug +define+SEQ=$seq +define+NUM=2  -l vlog_tb.log;
else
    vlog -timescale=1ns/1ns -sv +acc ${UVM_FLAGS} -incr -f filelist_tb.f -assertdebug +define+SEQ=$seq +define+NUM=6  -l vlog_tb.log;
fi 

#vlog -timescale=1ns/1ns -sv +acc ${UVM_FLAGS} -incr -f filelist_tb.f -assertdebug +define+SEQ=$seq  -l vlog_tb.log;
vlog -sv +acc -incr -f filelist_rtl.f -l vlog_rtl.log +cover=sbceft -assertdebug;
vsim -voptargs=+acc -sva -assertdebug -coverage tb_top -c -do "set WildcardFilter None;add wave -r tb_top/*; coverage save -onexit $seq.ucdb; run -all; quit;"

# vcover merge final_coverage.ucdb  *.ucdb;
# vsim -viewcov $seq.ucdb ;
