#!/bin/bash

#seq=TEST1
#seq=TEST2
#seq=TEST3
#seq=TEST4         
#seq=TEST5
#seq=TEST6         
#seq=TEST7
#seq=TEST8
#seq=TEST9
#seq=TEST10
#seq=TEST11
#seq=TEST12

rm -rf *.ucdb;

seq=( TEST1 TEST2 TEST3 TEST4 TEST5 TEST6 TEST7 TEST8 TEST9 TEST10 TEST11 TEST12 )
echo "${seq[@]}"

for seq_ins in "${seq[@]}"
do
	echo " Running $seq_ins ..................."
	rm -rf work; 
	vlib work; 

	UVM_FLAGS = +incdir+${UVM_HOME}/src ${UVM_HOME}/src/uvm_pkg.sv
    
    if [ "$seq_ins" == "TEST_10" ];
    then
        vlog -timescale=1ns/1ns -sv +acc ${UVM_FLAGS} -incr -f filelist_tb.f -assertdebug +define+SEQ=$seq_ins +define+NUM=2 -l vlog_tb.log;
    else
        vlog -timescale=1ns/1ns -sv +acc ${UVM_FLAGS} -incr -f filelist_tb.f -assertdebug +define+SEQ=$seq_ins +define+NUM=6 -l vlog_tb.log;
    fi
    vlog -sv +acc -incr -f filelist_rtl.f -l vlog_rtl.log +cover=sbceft -assertdebug;
    vsim -voptargs=+acc -sva -assertdebug -coverage tb_top -c -do "set WildcardFilter None;add wave -r tb_top/*; coverage save -onexit $seq_ins.ucdb; run -all; quit;"
done

vcover merge final_coverage.ucdb *.ucdb;
vsim -viewcov final_coverage.ucdb;
#cd covhtmlreport;
#firefox index.html;
#cd ..;
